# Shows a Sponsor ❤ button at the top of your repo.
# Replace lewisallena17 after you enable Sponsors at:
# https://github.com/sponsors/accounts
github: [lewisallena17]
custom: ['https://ltagb.gumroad.com/l/gferg']
