import type { Metadata } from 'next'
import Link from 'next/link'
import { readdirSync, readFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

export const metadata: Metadata = {
  title:       'Pantheon — Autonomous AI Agent Knowledge Base',
  description: 'Deep dives on building self-improving AI agents with Claude, Next.js, and Supabase. Open-source starter kit included.',
}

interface TopicMeta { slug: string; title: string; description: string }

function loadTopics(): TopicMeta[] {
  const dir = join(process.cwd(), 'app', 'topics')
  if (!existsSync(dir)) return []
  const slugs = readdirSync(dir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)

  const out: TopicMeta[] = []
  for (const slug of slugs) {
    const pagePath = join(dir, slug, 'page.tsx')
    if (!existsSync(pagePath)) continue
    try {
      const src = readFileSync(pagePath, 'utf8')
      const title = src.match(/title:\s*'([^']+)'/)?.[1] ?? slug
      const desc  = src.match(/description:\s*'([^']+)'/)?.[1] ?? ''
      out.push({ slug, title, description: desc })
    } catch {}
  }
  return out.sort((a, b) => a.slug.localeCompare(b.slug))
}

export default function TopicsIndex() {
  const topics = loadTopics()

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-10">
      <article className="max-w-3xl mx-auto">
        <nav className="text-[10px] font-mono text-slate-500 mb-6">
          <Link href="/" className="hover:text-cyan-400">◈ pantheon</Link>
          <span className="mx-2">/</span>
          <span>topics</span>
        </nav>

        <h1 className="text-3xl font-bold text-slate-100 mb-3">Pantheon Knowledge Base</h1>
        <p className="text-slate-300 leading-relaxed mb-8 text-lg">
          Practical articles on building autonomous AI agent systems. Every article is backed by working code in the
          <a href="https://github.com/lewisallena17/pantheon" className="text-cyan-400 hover:underline" target="_blank" rel="noopener noreferrer"> open-source repo</a>. New topics generated by the god agent itself.
        </p>

        {topics.length === 0 ? (
          <div className="text-slate-500 font-mono text-sm">No topics yet — god is still writing.</div>
        ) : (
          <ul className="space-y-4">
            {topics.map(t => (
              <li key={t.slug}>
                <Link href={`/topics/${t.slug}`} className="block group rounded border border-slate-800/60 bg-black/30 hover:border-cyan-800/60 p-4 transition-colors">
                  <h3 className="text-lg font-bold text-slate-100 group-hover:text-cyan-300 mb-1">{t.title}</h3>
                  <p className="text-[13px] text-slate-400 leading-relaxed">{t.description}</p>
                </Link>
              </li>
            ))}
          </ul>
        )}

        <footer className="mt-10 pt-6 border-t border-slate-800/60 text-[11px] font-mono text-slate-500 text-center">
          <Link href="/subscribe" className="text-cyan-500 hover:underline">get notified when new articles ship →</Link>
        </footer>
      </article>
    </main>
  )
}
